FROM python:3.10

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

# Install Node.js for Lighthouse
RUN apt-get update && apt-get install -y nodejs npm
RUN npm install -g lighthouse

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
