services:
  - type: web
    name: seo-audit-backend
    env: python
    buildCommand: update, run: pip install --upgrade pip && pip install -r requirements.txt && npm install
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
